### PR TITLE
Paclet compatibility

### PR DESCRIPTION
**Pull request by kubaPod**
The motivation was to update the repository to '.paclet standard'. Once a .paclet is build it can be attached to a GitHub project release as an asset. 

- PacletInfo.m was moved and updated in order to make .paclet generation work.

- Build.m was created 

  ``<<Build.m`` should build a *BayesianInference-x.y.z.paclet*

  Maintainer can attach the paclet to a release as an asset.

  User can download a paclet and install it with `PacletInstall @ paclet.paclet`.

   Alternatively there is an experimental way with [MPM package](https://github.com/kubaPod/MPM), it would only require user to run `MPMInstall["ssmit1986", "BayesianInference"]` (assuming ``MPM` `` is loaded)

### CODE REVIEW

**Comment by ssmit1986** [comment]
Sounds good. You probably know more about this than I do, at any rate :).

**Comment by kubaPod** [comment]
Great, so now you can go to https://github.com/ssmit1986/BayesianInference/releases draft or edit the release and drag a drop  created .paclet in the assets area below.

**Comment by ssmit1986** [comment]
I created and added the paclet, but when I run `PacletInstall[<file>]`, I cannot load the paclet with ``<<BayesianInference` ``. 

`PacletInformation["BayesianInference"]` indicates that it's there, but for some reason it won't load. Do you have any idea what the problem could be? I've had these sort of issues with paclets before and it's always a bit of a drag to figure out what's going on. `RestartPacletManager[]` and `RebuildPacletData[]` don't help either.

**Comment by kubaPod** [comment]
Indeed, somehow I missed that, maybe it cached something and worked for me.

Anyway, the fix seems to be to prepend ``"BayesianInference`",``  to the list of `"Context"` in *PacletInfo.m*.

I don't know why it is needed if that context does not exist. You can send greetings to TG for taking his time to document it.

p.s. I can create another pull request but since it is only a one line you can add it, right?

**Comment by ssmit1986** [comment]
I'll give it a shot; maybe I'll learn something ;).

**Comment by kubaPod** [comment]
Yes, it is a pain to get started but then it can help a lot because PacletManager is at each user's installation.

**Comment by ssmit1986** [comment]
Ok, I think that should do it. I hope I didn't screw over to much for other people by deleting the previous release tag. Sometimes it's just too tempting to rewrite history.

**Pull request merged**
